//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Background_H
#define METASPRITE_Background_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Background_TILE_ORIGIN 0
#define Background_TILE_W 8
#define Background_TILE_H 8
#define Background_WIDTH 160
#define Background_HEIGHT 144
#define Background_TILE_COUNT 235
#define Background_PALETTE_COUNT 1
#define Background_COLORS_PER_PALETTE 4
#define Background_TOTAL_COLORS 4
#define Background_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Background)

extern const palette_color_t Background_palettes[4];
extern const uint8_t Background_tiles[3760];

extern const unsigned char Background_map[360];

#endif
