//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Pond_H
#define METASPRITE_Pond_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Pond_TILE_ORIGIN 0
#define Pond_TILE_W 8
#define Pond_TILE_H 8
#define Pond_WIDTH 160
#define Pond_HEIGHT 144
#define Pond_TILE_COUNT 240
#define Pond_PALETTE_COUNT 1
#define Pond_COLORS_PER_PALETTE 4
#define Pond_TOTAL_COLORS 4
#define Pond_MAP_ATTRIBUTES 0

BANKREF_EXTERN(Pond)

extern const palette_color_t Pond_palettes[4];
extern const uint8_t Pond_tiles[3840];

extern const unsigned char Pond_map[360];

#endif
